Repository NUbots/NUbook, pull requests merged in 2022-11, with the labels that each got.

#267 Update folder in webots guide
  src/book/03-guides/02-tools/02-webots.mdx
Labels: bug

#237 Add page on battery handling
  src/book/03-guides/03-hardware/03-batteries.mdx
  src/book/03-guides/03-hardware/images/batteries/battery_in_robot.jpg
  src/book/03-guides/03-hardware/images/batteries/battery_monitor.jpg
  src/book/03-guides/03-hardware/images/batteries/charge.jpg
  src/book/03-guides/03-hardware/images/batteries/storage.jpg
Labels: documentation, enhancement

#262 Adds a NUClear tutorial
  src/book/03-guides/01-main-codebase/02-nuclear-tutorial.mdx
  src/book/03-guides/01-main-codebase/03-tuning-and-running-scripts.mdx
  src/book/03-guides/01-main-codebase/04-maintaining-subsystems.mdx
  src/book/03-guides/01-main-codebase/05-recording-playback.mdx
  src/book/03-guides/01-main-codebase/06-camera-calibration.mdx
Labels: documentation

#31 Add servo calibration page
  src/book/03-guides/03-hardware/02-servo-calibration.mdx
  src/book/03-guides/03-hardware/images/nugus.png
  src/book/03-guides/03-hardware/images/servo_calibration/discover.png
  src/book/03-guides/03-hardware/images/servo_calibration/error_status.png
  src/book/03-guides/03-hardware/images/servo_calibration/nugus_servo_axis.svg
  src/book/03-guides/03-hardware/images/servo_calibration/power_supply_and_comms.jpg
  src/book/03-guides/03-hardware/images/servo_calibration/scan.png
  src/book/03-guides/03-hardware/images/servo_calibration/servo_tool.jpg
  src/book/03-guides/03-hardware/images/servo_calibration/to_joint.png
  src/book/03-guides/03-hardware/images/servo_calibration/update_parameters.png
  src/book/03-guides/03-hardware/images/servo_calibration/usb.jpg
Labels: documentation, help wanted
