Repository NUbots/NUbook, pull requests merged in 2022-01, with the labels that each got.

#204 Add contributor list to contributions section
  src/components/contributions/contributions.jsx
  src/components/layout.jsx
  src/components/page-template.jsx
Labels: enhancement

#161 Documentation for autocompletion
  src/book/02-system/01-foundations/02-build-system.mdx
Labels: documentation

#206 Fix contributors component accessing undefined properties on new pages
  src/components/layout.jsx
Labels: bug
